local _,L = ...

-- Spanish (esES) localization added courtesy of Romanv_

if GetLocale()=="esES" then

-- Main.lua
	L["Rematch"] = "Rematch"
	L["Show/Hide Rematch"] = "Mostrar/Ocultar Rematch"
	L["Auto Load"] = "Carga automática"
	L["Team Notes"] = "Notas del equipo"
	L["Pets Tab"] = "Pestaña mascotas"
	L["Teams Tab"] = "Pestaña equipos"
	L["Queue Tab"] = "Pestaña cola"
	L["Toggle Rematch"] = "Alternar Rematch"
	L["Load this team?"] = "¿Cargar este equipo?"
	L["They do not appear to be online."] = "No parecen estar en línea."
	L["has also been added to your leveling queue!"] = "¡También se ha agregado a su cola de nivelación!"
	L["%s has also been added to your leveling queue!"] = "¡%s también se ha añadido a tu cola de subida de nivel!"
	L["The team named '%s' can't be found."] = "El equipo llamado '% s' no se puede encontrar."
	L["Rematch Debug Info"] = "Información de depuración de Rematch"

-- Utils.lua
	L["Leveling Pet"] = "Nivelación de mascotas"

-- Widgets\PetListButtons.lua
	L["A New Pet!"] = "¡Una nueva mascota!"
	L["Empty Battle Pet Slot"] = "Ranura de mascotas de batalla vacía"
	L["This pet can't level."] = "Esta mascota no puede nivelar."
	L["Only pets that can battle and are under 25 can go in the leveling queue."] = "Solo las mascotas que puedan luchar y que sean de nivel menor que 25 pueden entrar en la cola de nivelación."

-- Widgets\Toolbar.lua
	L["Total Pets"] = "Total:"
	L["Unique Pets"] = "Únicas:"
	L["Save As..."] = "Guardar como..."
	L["Save the currently loaded pets to a new team."] = "Guarda las mascotas actualmente cargadas en un nuevo equipo."
	L["Save the currently loaded pets to the loaded team."] = "Guarda las mascotas actualmente cargadas en el equipo cargado."
	L["Dismiss Pet"] = "Retirar mascota"
	L["Summon Pet"] = "Invocar mascota"
	L["Summons a random pet from your favorites."] = "Invocar una mascota aleatoria de tus favoritas."
	L["Random Favorite"] = "favorita aleatoria"
	L["Random From All"] = "aleatoria"
	L["Import Teams"] = "Importar equipos"
	L["Import a single team or many teams that were exported from Rematch."] = "Importar uno o varios equipos exportados desde Rematch."
	L["All pets are at full health."] = "Todas las mascotas están en plena salud."
	L["This treat's buff is already active."] = "El beneficio de esta golosina ya está activo."
	L["%s\n\nPets At Max Level: %s%d\124r\nPets Not Collected: %s%d\124r\n\n%s Click to display more about your collection."] = "%s\n\nMascotas a nivel máximo: %s%d\124r\nMascotas faltantes: %s%d\124r\n\n%s Haz clic para mostrar más sobre tu colección."

-- Widgets\MinimapButton.lua
    L["Toggle Window"] = "Alternar ventana"
	L["Load Favorite Team"] = "Cargar equipo favorito"
	L["Favorite Teams"] = "Equipos favoritos"

-- Widgets\PanelTabs.lua

-- Widgets\TextureHighlight.lua

-- Process\ODTables.lua

-- Process\PetInfo.lua
    L["Journal Is Locked"] = "El diario está bloqueado"
	L["Wrong Faction"] = "Facción incorrecta"
	L["Wrong Covenant"] = "Curia incorrecta"
	L["Ignored Pet"] = "Mascota ignorada"
	L["Random %s"] = "Aleatoria %s"
	L["Random Pet"] = "Mascota aleatoria"
	L["Unknown"] = "Desconocido"
	L["Can't Summon"] = "No se puede invocar"

-- Process\TeamInfo.lua

-- Process\PetTag.lua

-- Process\PetLoading.lua
	L["You can't load a team during combat."] = "No puedes cargar un equipo durante el combate."
	L["You can't load a team during a pet battle."] = "No puedes cargar un equipo durante una batalla de mascotas."
	L["You can't load a team in a matched pet battle."] = "No puedes cargar un equipo en una batalla de mascotas emparejadas."
	L["Pets are missing from this team!"] = "¡Las mascotas no están en este equipo!"
	L["Substitutes were found. Please review the loaded team and click Save if you'd like to keep the chosen pets."] = "Se encontraron sustitutos. Revise el equipo cargado y haga clic en Guardar si desea conservar las mascotas elegidas."
	L["Don't Warn About Missing Pets"] = "No advertir sobre las mascotas perdidas"

-- Process\Roster.lua

-- Process\Filters.lua
	L["Favorites"] = "Favoritas"
	L["Types"] = "Tipos"
	L["Strong Vs"] = "Fuerte Vs"
	L["Tough Vs"] = "Duro Vs"
	L["Breed"] = "Raza"
	L["Similar"] = "Similar"
	L["Script"] = "Guión"
	L["Moveset"] = nil
	L["Level"] = "Nivel"
	L["Leveling"] = "Nivelación"
	L["Tradable"] = "Comerciable"
	L["Battle"] = "Batalla"
	L["Quantity"] = "Cantidad"
	L["Team"] = "Equipo"
	L["Hidden"] = "Oculto"
	L["Zone"] = "Zona"
	L["Notes"] = "Notas"
	L["Search"] = "Buscar"
	L["Sort"] = "Ordenar"
	L["Stats Search"] = "Buscar estadísticas"

-- Process\PetList.lua

-- Process\QueueProcess.lua
	L["Now leveling:"] = "Es el turno de:"
	L["Rematch's leveling queue is empty"] = "La cola de nivelación de Rematch está vacía"
	L["All done leveling pets!"] = "¡Todas las mascotas han subido de nivel!"

-- Process\Sanctuary.lua

-- Process\TeamStrings.lua
	L["%s (NPC#%d)"] = nil
	L["%s (%s NPC#%d)"] = nil
	L["%d: %s"] = nil
	L["%d: %s (%d,%d,%d)"] = nil
	L["Preferred leveling pets: %s."] = "Mascotas preferidas para subir de nivel: %s."
	L["at least %d health"] = "al menos %d de salud"
	L["at least %d health (or any Magic/Mechanical)"] = "al menos %d de salud (o cualquier Mágica/Mecánica)"
	L["at least %d health (%s damage expected)"] = "al menos %d de salud (%s daño esperado)"
	L["at least %d health (or any Magic/Mechanical, %s damage expected)"] = "al menos %d de salud (o cualquier Mágica/Mecánica, %s daño esperado)"
	L["at most %d health"] = "a lo sumo %d de salud"
	L["at least level %s"] = "al menos nivel %s"
	L["at most level %s"] = "a lo sumo nivel %s"

-- Process\SpecialSlots.lua
	L["Leveling Slot"] = "Ranura de nivelación"
	L["This slot is controlled by the leveling queue.\n\nTeams saved with leveling slots will load leveling pets from the queue into these slots."] = "Esta ranura está controlada por la cola de nivelación.\n\nLos equipos guardados con ranuras de nivelación cargarán mascotas de nivelación en estas ranuras."
	L["Ignored Slot"] = "Ranura ignorada"
	L["Teams saved with ignored slots will not load anything into these slots."] = "Los equipos guardados con ranuras ignoradas no cargarán nada en estas ranuras."
	L["Random %s Pet"] = "Mascota aleatoria %s"
	L["Teams saved with random slots will load a random high level pet into these slots."] = "Los equipos guardados con ranuras aleatorias cargarán una mascota aleatoria de alto nivel en estas ranuras."

-- Menus\Menu.lua
	L["Help"] = "Ayuda"

-- Menus\TeamMenus.lua
	L["Edit Win Record"] = "Editar registro de victorias"
	L["Change Name Or Target"] = "Cambiar nombre u objetivo"
	L["Edit Team"] = "Editar equipo"
	L["Set Notes"] = "Establecer notas"
	L["Leveling Preferences"] = "Preferencias de nivelación"
	L["Move To"] = "Mover a "
	L["Move To Top"] = "Mover al principio"
	L["Move Up"] = "Mover hacia arriba"
	L["Move Down"] = "Mover hacia abajo"
	L["Move To End"] = "Mover al final"
	L["Share"] = "Compartir"
	L["Delete this team?"] = "¿Borrar este equipo?"
	L["Unload Team"] = "Retirar equipo"
	L["Put Leveling Pet Here"] = "Colocar mascota para nivelar aquí"
	L["Add a leveling pet to this team?"] = "¿Agregar una mascota de nivelación a este equipo?"
	L["About Teams"] = "Acerca de los equipos"
	L["Teams named in %sWhite\124r have a target stored within them.\nTeams named in Gold do not.\n\n%sTo change pets or abilities in a team:\124r\n1) Load the team.\n2) Make any changes.\n3) Click Save at the bottom of the window."] = "Los equipos nombrados en %sBlanco\124r tienen un objetivo almacenado dentro de ellos.\nLos equipos nombrados en Dorado no.\n\n%sPara cambiar mascotas o habilidades en un equipo:\124r\n1) Cargar el equipo.\n2) Hacer cualquier cambio.\n3) Click en guardar en la parte inferior de la ventana."
	L["Copy As Plain Text"] = "Copiar como texto sin formato"
	L["Format this team into plain text to copy elsewhere, such as forums or emails.\n\nThe plain text format is best for sharing a team with others that may not use Rematch."] = "Formatea este equipo en texto sin formato para copiarlo en otros lugares, como foros o correos electrónicos.\n\nEl formato de texto sin formato es el mejor para compartir un equipo con otras personas que no utilizan Rematch."
	L["Export Team"] = "Exportar equipo"
	L["Export this team as a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can paste this team into their Rematch via Import Team."] = "Exporta este equipo como una cadena que puede copiar en otro lugar, como foros o correos electrónicos.\n\nOtros usuarios de Rematch pueden pegar este equipo en su juego a través de Importar equipo."
	L["Import Team"] = "Importar equipo"
	L["Send Team"] = "Enviar equipo"
	L["Sharing is disabled in options."] = "Compartir está deshabilitado en las opciones."
	L["Send this team to another online user of Rematch."] = "Envía este equipo a otro usuario en línea de Rematch."
	L["Prompt To Load"] = "Preguntar para cargar"
	L["When your new target has a saved team not already loaded, and the target panel isn't on screen, display a popup asking if you want to load the team.\n\nThis is only for the first interaction with a target. You can always load a target's team from the target panel."] = "Cuando tu nuevo objetivo tenga un equipo guardado que aún no esté cargado y el panel de objetivos no esté en la pantalla, mostrar una ventana emergente que te pregunte si deseas cargar el equipo.\n\nEsto es solo para la primera interacción con un objetivo. Siempre puedes cargar el equipo de un objetivo desde el panel de objetivos."
	L["With Rematch Window"] = "Con ventana de Rematch"
	L["Prompt to load with the Rematch window instead of a separate popup dialog."] = "Solicitar que se cargue con la ventana Rematch en lugar de un diálogo emergente separado."
	L["Always Prompt"] = "Siempre preguntar"
	L["Prompt every time you interact with a target with a saved team not already loaded, instead of only the first time."] = "Preguntar cada vez que interactúe con un objetivo con un equipo guardado que no se haya cargado, en lugar de solo la primera vez."
	L["When you mouseover a new target that has a saved team not already loaded, immediately load it.\n\nThis is only for the first interaction with a target. You can always load a target's team from the target panel."] = "Cuando pases el cursor sobre un nuevo objetivo que tiene un equipo guardado que aún no está cargado, se cargara inmediatamente.\n\nEsto es solo para la primera interacción con un objetivo. Siempre puedes cargar el equipo de un objetivo desde el panel de objetivos."
	L["Show After Loading"] = "Mostrar después de cargar"
	L["After a team auto loads, show the Rematch window."] = "Después de que un equipo se cargue automáticamente, mostrar la ventana de Rematch"
	L["Show On Injured"] = "Mostrar con heridos"
	L["When a team auto loads, show the Rematch window if any pets are injured."] = "Cuando un equipo se carga automáticamente, muestra la ventana Rematch si alguna mascota está herida."
	L["On Target Only"] = "Solo en objetivo"
	L["Auto load upon targeting only, not mouseover.\n\n\124cffff4040WARNING!\124r This is not recommended! It can be too late to load pets if you target with right-click!"] = "Carga automática solo al apuntar, no al pasar el cursor.\n\n\124cffff4040¡ADVERTENCIA!\124r ¡Esto no se recomienda! ¡Puede ser demasiado tarde para cargar mascotas si apuntas con el botón derecho!"
	L["Export Listed Teams"] = "Exportar equipos guardados"
	L["Export all teams listed below to a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can then paste these teams into their Rematch via Import Teams.\n\nYou can export a single team by right-clicking one and choosing its Share menu."] = "Exporta todos los equipos guardados a una cadena que puedes copiar en otro lugar, como foros o correos electrónicos.\n\nOtros usuarios de Rematch pueden pegar estos equipos en su juego a través de Importar equipos.\n\nPuedes exportar un solo equipo haciendo click derecho y eligiendo el menú Compartir."
	L["Backup All Teams"] = "Copia de seguridad de todos los equipos"
	L["This will export all teams across all tabs into text that you can paste elsewhere, such as an email to yourself or a text file someplace safe. You can later restore these teams with the Import Teams option."] = "Esto exportará todos los equipos en todas las pestañas en un texto que puedes pegar en otro lugar, como un correo electrónico para ti mismo o un archivo de texto en un lugar seguro. Más tarde puedes restaurar estos equipos con la opción Importar equipos."
	L["Import From Pet Battle Teams"] = "Importar desde Pet Battle Teams"
	L["Copy your existing teams from Pet Battle Teams to Rematch."] = "Copia tus equipos existentes de Pet Battle Teams a Rematch."
	L["Import From Niggles: Pet Teams"] = "Importar de Niggles: equipos de mascotas"
	L["Copy your existing teams from Niggles: Pet Teams to Rematch."] = "Copia tus equipos existentes de Niggles: equipos de mascotas a Rematch."

-- Menus\PetMenus.lua
	L["Unnamed Pets"] = "Mascotas sin nombre"
	L["-- Collected pets that still have their original name.\n\nreturn owned and not customName"] = "Mascotas coleccionadas que todavía tienen su nombre original.\n\nRegresar propiedad y quitar personalizado"
	L["Partially Leveled"] = "Parcialmente nivelada"
	L["-- Pets that have earned some xp in battle.\n\nreturn xp and xp>0"] = "-- Mascotas que han ganado algo de XP en combate.\n\ndevolver xp y xp>0"
	L["Unique Abilities"] = "Habilidades únicas"
	L["-- Pets with abilities not shared by other pets.\n\nif not count then\n  -- create count of each ability per species\n  count = {}\n  for speciesID in AllSpeciesIDs() do\n    for abilityID in AllAbilities(speciesID) do\n      if not count[abilityID] then\n        count[abilityID] = 0\n      end\n      count[abilityID] = count[abilityID] + 1\n    end\n  end\nend\n\nfor _,abilityID in ipairs(abilityList) do\n  if count[abilityID]==1 then\n    return true\n  end\nend"] = nil
	L["Pets Without Rares"] = "Mascotas sin Raros"
	L["-- Collected battle pets that have no rare version.\n\nif not rares then\n  rares = {}\n  for petID in AllPetIDs() do\n    if select(5,C_PetJournal.GetPetStats(petID))==4 then\n      rares[C_PetJournal.GetPetInfoByPetID(petID)]=true\n    end\n  end\nend\n\nif canBattle and owned and not rares[speciesID] then\n  return true\nend"] = nil
	L["Hybrid Counters"] = "Contadores híbridos"
	L["-- Pets with three or more attack types different than their pet type.\n\nlocal count = 0\nfor _,abilityID in ipairs(abilityList) do\n  local abilityType,noHints = select(7, C_PetBattles.GetAbilityInfoByID(abilityID) )\n  if not noHints and abilityType~=petType then\n    count = count + 1\n  end\nend\n\nreturn count>=3\n"] = nil
	L["Find Similar"] = "Encontrar similar"
	L["Enter a new name"] = "Ingresar un nuevo nombre"
	L["Any Type"] = "Cualquier tipo"
	L["Find Moveset"] = "Encontrar conjunto de moviemientos"
	L["List %d Teams"] = "Listar %d Equipos"
	L["Hide Pet"] = "Ocultar mascota"
	L["Unhide Pet"] = "Mostrar mascota"
	L["Slotted pets cannot be released."] = "Las mascotas ranuradas no pueden ser liberadas."
	L["Release this pet?"] = "¿Liberar esta mascota?"
	L["Once released, this pet is gone forever!"] = "¡Una vez liberada, esta mascota se ha irá para siempre!"
	L["Slotted pets cannot be caged."] = "Las mascotas ranuradas no pueden ser enjauladas."
	L["Injured pets cannot be caged."] = "Las mascotas heridas no pueden ser enjauladas."
	L["Cage this pet?"] = "¿Enjaular esta mascota?"
	L["Start Leveling"] = "Comenzar nivelación"
	L["Add To Leveling Queue"] = "Agregar a la cola de nivelación"
	L["Stop Leveling"] = "Detener nivelación"
	L["Only Favorites"] = "Solo favoritos"
	L["Favorite Filters"] = "Filtros favoritos"
	L["Pet Filter"] = "Filtro de mascota"
	L["In addition to the filters in this menu, you can further refine the pet list with the search box. Some search examples:\n\nPets: %sBlack Tabby\124r\nZones: %sSilithus\124r\nAbilities: %sSandstorm\124r\nText in abilities: %sBleed\124r\nLevels: %slevel=21-23\124r\nStats: %sspeed>300\124r\n\nSearches in \"quotes\" will limit results to only complete matches.\n\nSearch results will be sorted by relevance unless the option %sDon't Sort By Relevance\124r is checked in the Options tab."] = nil
	L["Reset All"] = "Restablecer todo"
	L["Checkbox Groups"] = "Casilla de verificación grupos"
	L["In filter menus, checkbox groups assume if nothing is checked you want to view all choices.\n\nYou can also:\n\n%s[Shift]+Click\124r to check all except the box clicked.\n\n%s[Alt]+Click\124r to uncheck all except the box clicked."] = nil
	L["Low Level (1-7)"] = "Nivel bajo (1-7)"
	L["Mid Level (8-14)"] = "Nivel medio (8-14)"
	L["High Level (15-24)"] = "Nivel alto (15-24)"
	L["Max Level (25)"] = "Nivel máximo (25)"
	L["Without Any 25s"] = "Sin ningún 25"
	L["Moveset Not At 25"] = nil
	L["You can filter to a specific level or range of levels in the search box. For example, search for:\n\n\%slevel=1\124r\nor\n\%slevel=21-23\124r"] = nil
	L["All breed data is pulled from your installed %s%s\124r addon.\n\nThe breed \"New\" categorizes pets with no breed data. Keep your breed addon up to date to see if they have new data."] = nil
	L["Not Leveling"] = "No nivelación"
	L["Not Tradable"] = "No comerciable"
	L["Can Battle"] = "Puede luchar"
	L["Can't Battle"] = "No puede luchar"
	L["One Copy"] = "Una copia"
	L["Two+ Copies"] = "Más de dos copias"
	L["Three+ Copies"] = "Más de tres copias"
	L["In A Team"] = "En un equipo"
	L["Not In A Team"] = "No en un equipo"
	L["Unique Moveset"] = nil
	L["Shared Moveset"] = nil
	L["Current Zone"] = "Zona actual"
	L["Hidden Pets"] = "Mascotas ocultas"
	L["Has Notes"] = "Tiene notas"
	L["Reverse Sort"] = "Orden inverso"
	L["Favorites First"] = "Favoritas primero"
	L["Sort By"] = "Ordenar por"
	L["You can filter to a specific range of stats too. For example, search for:\n\n\%shealth>500\124r\nor\n\%sspeed=200-300\124r\n\nThe sort order is not ordinarily reset when filters are reset. The option %sReset Sort With Filters\124r in the Options tab will reset the sort when you reset the filters."] = nil
	L["Find Pets With This Ability"] = "Encontrar mascotas con esta habilidad"
	L["Put Random Pet Here"] = "Colocar una mascota aleatoria aquí"
	L["Ignore This Slot"] = "Ignorar esta ranura"
	L["Stop Leveling This Slot"] = "Deja de nivelar esta ranura"
	L["Stop Randomizing This Slot"] = "Deja de aleatorizar esta ranura"
	L["Stop Ignoring This Slot"] = "Dejar de ignorar esta ranura"
	L["Hide this pet?"] = "¿Ocultar esta mascota?"
	L["Don't Ask When Hiding Pets"] = "No preguntar cuando ocultar mascotas"
	L["Are you sure you want to hide all versions of %s%s\124r?\n\nHidden pets will not show up in the pet list or searches. You can view or unhide these pets in the 'Other' filter."] = nil
	L["Save Filter"] = "Guardar filtro"
	L["A filter must be active before it can be saved."] = "Un filtro debe estar activo antes de que pueda guardarse."
	L["Save this as a favorite filter?"] = "¿Guardar esto como un filtro favorito?"
	L["Filters: %s%s\124r\n\nChoose a name to use in the Favorite Filters menu:"] = "Filtros: %s%s\124r\n\nElige un nombre para usar en el menú Filtros favoritos:"
	L["Note: Search text and Sort order are not included in the filter."] = "Nota: el texto de búsqueda y el orden de clasificación no se incluyen en el filtro."
	L["Delete Filter"] = "Borrar filtro"
	L["Are you sure you want to delete the filter named %s%s\124r?"] = "¿Estás seguro de que deseas eliminar el filtro llamado %s%s\124r?"
	L["New Script"] = "Nuevo guión"
	L["Create a new pet filter."] = "Crear un nuevo filtro para mascotas."
	L["Script Filters"] = "Filtros de guión"
	L["This allows you to create custom pet filters with a little bit of Lua code. See the reference buttons at the top of the New Script dialog for details.\n\nTo view or edit an existing script, click the Gear icon beside the script in the menu above."] = nil
	L["Delete Script"] = "Borrar guión"
	L["Are you sure you want to delete the script named %s%s\124r?"] = "¿Estás seguro de que quieres eliminar el guión llamado? %s%s\124r?"

-- Menus\TargetData.lua
	L["Menagerie"] = "Corral"
	L["Beasts of Fable"] = "Bestias de fábula"

-- Menus\TargetMenus.lua
	L["Imported Team"] = "Equipo importado"
	L["Noteworthy Targets"] = "Objetivos destacados"
	L["These are noteworthy targets such as tamers and legendary pets.\n\nChoose one to view the pets you would battle.\n\nTargets with a \124TInterface\\RaidFrame\\ReadyCheck-Ready:14\124t have a team saved."] = nil
	L["No Target"] = "Sin objetivo"

-- Dialogs\Dialog.lua
	L["Tab:"] = "Pestaña:"

-- Cards\PetCard.lua
	L["Damage\nTaken"] = "Daño\nRecibido"
	L["from"] = "desde"
	L["abilities"] = "habilidades"
	L["Unpin Pet Card"] = "Desanclar tarjeta de mascota"
	L["While pinned, the pet card will display where you last moved it.\n\nClick this to unpin the pet card and snap it back to the pets."] = "Mientras está anclada, la tarjeta de mascota se mostrará donde la movió por última vez.\n\nHaz click aquí para desanclar la tarjeta de mascota y volver a colocarla en las mascotas."
	L["Pet Card"] = "Ficha de mascota"
	L["Hold [Alt] to view more about this pet."] = "Mantén presionado [Alt] para ver más sobre esta mascota."
	L["XP: %d/%d (%d%%)"] = nil
	L["Possible Breeds"] = "Posibles razas"
	L["\124cffff0000Revoked"] = "\124cffff0000Revocado"
	L["Revoked"] = "Revocado"
	L["This pet has been revoked, which means Blizzard withdrew your ability to use this pet.\n\nThis commonly happens when a pet no longer meets a condition for ownership, such as the Core Hound Pup requiring an authenticator attached to the account."] = nil
	L["This pet can't be summoned."] = "Esta mascota no puede ser invocada."
	L["Slotted"] = "Insertado"
	L["This pet is loaded in one of the three battle pet slots."] = "Esta mascota se carga en una de las tres ranuras para mascotas de batalla."
	L["Favorite"] = "Favorita"
	L["This pet is marked as a Favorite from its right-click menu."] = "Esta mascota está marcada como favorita en el menú del botón derecho."
	L["Determines how stats are distributed.  All breed data is pulled from your installed %s%s\124r addon."] = "Determina cómo se distribuyen las estadísticas. Todos los datos de raza se extraen de su complemento %s%s\124r instalado."
	L["Species ID"] = "Especie ID"
	L["All versions of this pet share this unique \"species\" number."] = "Todas las versiones de esta mascota comparten este número único de \"species\" ."
	L["This pet is in Rematch's leveling queue."] = "Esta mascota está en la cola de nivelación de Rematch."
	L["%d Teams"] = "%d Equipos"
	L["Teams"] = "Equipos"
	L["%s Click to search for all teams that include this pet."] = "%s Haz click para buscar todos los equipos que incluyen a esta mascota."
	L["%s Click to search for all versions of this pet."] = "%s Haz click para buscar todas las versiones de esta mascota."
	L["When this team loads, your current leveling pet will go in this spot."] = "Cuando este equipo se cargue, su mascota de nivelación actual ocupará este lugar."
	L["When this team loads, this spot will be ignored."] = "Cuando este equipo se cargue, este lugar será ignorado."
	L["When this team loads, a random high level pet will go in this spot."] = "Cuando este equipo se cargue, una mascota de alto nivel aleatorio ocupará este lugar."
	L["This is an opponent pet."] = "Esta es una mascota oponente."
	L["All breed data pulled from %s%s\124r."] = "Todos los datos de raza extraídos de %s%s\124r."
	L["Stats At Level 25 \124cff0070ddRare"] = "Estadísticas en el nivel 25 \124cff0070ddRare"
	L["No known breeds :("] = "No se conocen razas :("

-- Cards\AbilityCard.lua
	L["Vs"] = "Vs"
	L["%s\n\n\124TInterface\\WorldMap\\Gear_64Grey:16:16:0:0:64:64:8:56:6:57\124t %sAbility ID: %d"] = nil

-- Cards\Notes.lua
    L["Team Notes"] = "Notas de equipo"
	L["Pet Notes"] = "Notas de mascotas"
	L["Delete Notes"] = "Borrar notas"
	L["Are you sure you want to delete the notes for %s\124r?"] = "¿Estás seguro de que desea eliminar las notas para% s \ 124r?"

-- Cards\WinRecord.lua
	L["Win Record"] = "Récord de victorias"
	L["Hold [Alt] to view totals for all teams."] = "Presiona [Alt] para ver los totales de todos los equipos."
	L["Wins:"] = "Victorias:"
	L["Losses:"] = "Derrotas:"
	L["Draws:"] = "Empates:"
	L["Totals Across All Teams"] = "Totales de todos los equipos"
	L["%s%s\124r Battles"] = "%s%s\124r Batallas"
	L["Reset Win Record"] = "Restablecer registro de victorias"
	L["Are you sure you want to remove all wins, losses and draws from the team \"%s\"?"] = "¿Estás seguro de que quieres eliminar todas las victorias, derrotas y empates del equipo\"%s\"?"
	L["Reset All Win Records"] = "Restablecer todos los registros de victorias"
	L["Are you sure?"] = "¿Estás seguro?"
	L["This will remove win record data for all teams and cannot be undone!"] = "¡Esto eliminará los datos de registro de victorias para todos los equipos y no se puede deshacer."
	L["Convert Team Names To Win Records"] = "Convertir los nombres de los equipos para ganar récords"
	L["Convert"] = "Convertir"
	L["This will look for teams with names that may include win-loss-draw stats and pull those into an actual win record before removing the numbers from the team name.\n\nDo you want to convert these teams?\n\nThe currently loaded team will be unloaded to prevent major complications.\n\n\124cffff1111Please backup your teams before attempting this!"] = "Esto buscará equipos con nombres que puedan incluir estadísticas de victorias-derrotas-empates y los incorporará a un registro de victorias real antes de eliminar los números del nombre del equipo.\n\n¿Desea convertir estos equipos?\n\nLos cargados actualmente El equipo se descargará para evitar complicaciones importantes.\n\n\124cffff1111¡Por favor, haga una copia de seguridad de sus equipos antes de intentar esto!"
	L["Done!"] = "¡Hecho!"
	L["%s%d teams and %d battles were converted."] = "Se han convertido %s%d equipos y %d batallas."

-- Panels\PetPanel.lua
    L["Search Pets"] = "Buscar mascotas"
	L["Strong vs"] = "Fuerte contra"
	L["Tough vs"] = "Duro contra"
	L["Quality"] = "Calidad"
	L["Pets: %s%d"] = "Mascotas: %s%d"
	L["Filters: %s%s"] = "Filtros: %s%s"

-- Panels\LoadoutPanel.lua
	L["Target has a saved team"] = "El objetivo tiene un\r\nequipo guardado"
	L["Load"] = "Cargar"
	L["Load the team saved for this target."] = "Cargar el equipo guardado para este objetivo."
	L["This target has no saved team"] = "Este objetivo no tiene un\r\nequipo guardado."
	L["Save the currently loaded pets to this target."] = "Guardar las mascotas actualmente cargadas en este objetivo."

-- Panels\TeamPanel.lua
	L["Search Teams"] = "Buscar equipos"

-- Panels\QueuePanel.lua
	L["Ascending Level"] = "Nivel ascendente"
	L["Descending Level"] = "Nivel descendente"
	L["Median Level"] = "Nivel medio"
	L["Type"] = "Tipo"
	L["Queue"] = "Cola"
	L["This is the leveling queue. Drag pets you want to level here.\n\nRight click any of the three battle pet slots and choose 'Put Leveling Pet Here' to mark it as a leveling slot you want controlled by the queue.\n\nWhile a leveling slot is active, the queue will fill the slot with the top-most pet in the queue. When this pet reaches level 25 (gratz!) it will leave the queue and the next pet in the queue will take its place.\n\nTeams saved with a leveling slot will reserve that slot for future leveling pets."] = "Esta es la cola de nivelación. Arrastra las mascotas que deseas nivelar aquí.\n\nHaz click derecho en cualquiera de las tres ranuras para mascotas de duelo y elige: 'Colocar mascota para nivelar aquí' para marcarla como una ranura de nivelación que deseas controlar por la cola.\n\nMientras un espacio de nivelación este activo, la cola llenará el espacio con la mascota más alta en la lista de espera. Cuando esta mascota alcance el nivel 25, dejará la cola y la próxima mascota en la lista tomará su lugar.\n\nLos equipos guardados con una ranura de nivelación reservarán esa ranura para futuras mascotas."
	L["Sort by:"] = "Ordenar por:"
	L["Sort all pets in the queue from level 1 to level 24."] = "Ordenar todas las mascotas en la cola del nivel 1 al nivel 24."
	L["Sort all pets in the queue for levels closest to 10.5."] = "Ordenar todas las mascotas en la cola para los niveles más cercanos a 10.5."
	L["Sort all pets in the queue from level 24 to level 1."] = "Ordenar todas las mascotas en la cola del nivel 24 al nivel 1."
	L["Sort all pets in the queue by their types."] = "Ordenar todas las mascotas en la cola por sus tipos."
	L["Group favorites to the top of the queue."] = "Agrupar los favoritos en la parte superior de la cola."
	L["Rares First"] = "Poco comunes primero"
	L["Group rares to the top of the leveling queue."] = "Agrupar poco comunes en la parte superior de la cola de nivelación."
	L["Active Sort"] = "Activar ordenamiento"
	L["The queue will stay sorted in the order chosen. The order of pets may automatically change as they gain xp or get added/removed from the queue.\n\nYou cannot manually change the order of pets while the queue is actively sorted."] = "La cola permanecerá ordenada en el orden elegido. El orden de las mascotas puede cambiar automáticamente a medida que ganan XP o se agregan o eliminan de la cola.\n\nNo puedes cambiar manualmente el orden de las mascotas mientras el ordenamiento de la cola está activo."
	L["Pause Preferences"] = "Preferencias de pausa"
	L["Suspend all preferred loading of pets from the queue, except for pets that can't load."] = "Suspender toda la carga preferida de mascotas de la cola, excepto las mascotas que no se pueden cargar."
	L["Fill Queue"] = "Rellenar cola"
	L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, and for which you don't have a level 25 or one in the queue already."] = "Llenar la cola de nivelación con una versión de alguna mascota que pueda subir de nivel de la lista de mascotas filtrada y para la cual no tienes una a nivel 25 o una en la cola ya."
	L["Fill Queue More"] = "Rellenar más la cola"
	L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, regardless whether you have any at level 25 or one in the queue already."] = "Llenar la cola de nivelación con una versión de alguna mascota que puede subir de nivel de la lista de mascotas filtrada, independientemente de si tienes alguna en el nivel 25 o una en la cola ya."
	L["Empty Queue"] = "Limpiar cola"
	L["Remove all leveling pets from the queue."] = "Eliminar todas las mascotas de nivelación de la cola."
	L["Are you sure you want to remove all pets from the leveling queue?"] = "¿Estás seguro de que deseas eliminar todas las mascotas de la cola de nivelación?"
	L["Leveling Queue"] = "Cola de nivelación"
	L["No Active Sort"] = "No activar ordenamiento"
	L["Turn off Active Sort. Queued pets can then be rearranged and will not automatically reorder themselves.\n\nTo turn Active Sort back on, check %sActive Sort\124r in the Queue menu."] = "Desactivar Ordenamiento automatico. Las mascotas en cola se pueden reorganizar y no se reordenarán automáticamente.\n\nPara volver a activarlo, marca %sOrdenamiento activo\124r en el menú Cola."
	L["Turn Off Active Sort?"] = "¿Desactivar el ordenamiento activo?"
	L["This pet is already in the queue and Active Sort is enabled.\n\nWhile enabled, the queue has complete control over the order of pets in the queue.\n\nDo you want to turn off Active Sort to move this pet in the queue?"] = "Esta mascota ya está en la cola y el ordenamiento automatico está activado.\n\nMientras está activo, la cola tiene control total sobre el orden de las mascotas.\n\n¿Deseas desactivar el ordenamiento automatico para mover esta mascota en la cola? ¿cola?"
	L["Leveling Pets: %s%s"] = "Mascotas de nivelación: %s%s"
	L["Active Sort:"] = "Ordenamiento activo: "
	L["Add these pets to the queue?"] = "¿Agregar estas mascotas a la cola?"
	L["This will add %s%d\124r pets to the leveling queue.\n\nYou can be more selective by filtering pets.\n\nFor instance, if you filter pets to High Level (15-24) and Rare, Fill Queue will only add rare pets between level 15 and 24."] = "Esto agregará %s%d\124r mascotas a la cola de nivelación.\n\nPuedes ser más selectivo al filtrar mascotas.\n\nPor ejemplo, si filtras mascotas a nivel alto (15-24) y raras, completar la cola solo agregará mascotas raras entre el nivel 15 y 24."
	L["This will add %s%d\124r pets to the leveling queue."] = "Esto agregará %s%d\124r mascotas a la cola de nivelación."

-- Panels\MiniQueue.lua

-- Panels\MiniPanel.lua
	L["This target has a saved team"] = "Este objetivo tiene un equipo guardado."

-- Panels\OptionPanel.lua
	L["Search Options"] = "Buscar opciones"
	L["Anchor"] = "Anclaje"
	L["Notes Font Size \124TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:12:12\124t"] = nil
	L["Small"] = "Pequeño"
	L["Normal"] = "Normal"
	L["Large"] = "Grande"
	L["Notes Font Size"] = "Tamaño de letra de las notas"
	L["This determines the size of text within pet and team notes."] = "Esto determina el tamaño del texto dentro de las notas de la mascota y del equipo."
	L["Click here to choose a different scale for the standalone window."] = "Haz click aquí para elegir una escala diferente para la ventana independiente."
	L["%s\n\n%sWARNING!\124r There may be an issue with pet toasts in ElvUI not positioning properly. While using ElvUI it's recommended pet toasts remain hidden unless you've moved alerts in ElvUI."] = nil
	L["ElvUISkin version %s"] = nil
	L["Current Scale: %d%%"] = "Escala actual: %d%%"
	L["Bottom Right"] = "Abajo a la derecha"
	L["Top Right"] = "Arriba a la derecha"
	L["Bottom Left"] = "Abajo a la izquierda"
	L["Top Left"] = "Arriba a la izquierda"
	L["Anchor: %s"] = "Anclaje: %s"
	L["When the standlone window is minimized, send it to the %s corner."] = "Cuando la ventana independiente esté minimizada, enviarla a la esquina %s."
	L["Reload the UI now?"] = "¿Recargar la UI ahora?"
	L["You've chosen to change the setting for %s.\n\nThis change doesn't take effect until a reload or logout."] = "Has elegido cambiar la configuración de %s.\n\nEste cambio no surtirá efecto hasta que se vuelva a cargar o se cierre la sesión.."
	L["Custom Scale"] = "Escala personalizada"
	L["Keep this scale?"] = "Mantener estas escala"
	L["This scale determines the relative size of the standalone window, where 100% is the standard size."] = "Esta escala determina el tamaño relativo de la ventana independiente, donde 100 % es el tamaño estándar."

-- Panels\OptionList.lua
	L["All Options"] = "Todas las opciones"
	L["Targeting Options"] = "Opciones de objetivo"
	L["When a team auto loads, show the Rematch window if any pets in the team are injured."] = "Cuando un equipo se carga automáticamente, muestra la ventana de Rematch si alguna mascota del equipo está herida."
	L["Auto load upon targeting only, not mouseover.\n\n\124cffff4040WARNING!\124r This is not recommended! It can be too late to load pets if you target with right click!"] = "Carga automática sólo al apuntar, no al pasar el ratón por encima.\n\n\124cffff4040¡ADVERTENCIA!\124r ¡Esto no es recomendable! ¡Puede ser demasiado tarde para cargar mascotas si apuntas con el click derecho!"
	L["Always Show When Targeting"] = "Mostrar siempre que se seleccione un objetivo"
	L["Regardless whether a target's team is already loaded, show the Rematch window when you target something with a saved team."] = "Independientemente de si el equipo de un objetivo ya está cargado, muestra la ventana de Rematch cuando apuntas a algo con un equipo guardado."
	L["Load Teams From Target Button"] = "Cargar equipos desde el botón objetivo"
	L["When a target is chosen after clicking the Target button above the loaded pets, automatically load any saved team associated with the target."] = "Cuando se elige un objetivo después de hacer clic en el botón Objetivo sobre las mascotas cargadas, carga automáticamente cualquier equipo guardado asociado con el objetivo."
	L["Use Old Target Button Menu"] = "Usar el antiguo botón menú de objetivo"
	L["When clicking the Target button above the loaded pets, use the old context menu rather than the scrollable list of targets to select from."] = "Al hacer click en el botón Objetivo situado encima de las mascotas cargadas, se utiliza el antiguo menú contextual en lugar de la lista desplegable de objetivos para seleccionar."
	L["Preferred Window Mode"] = "Modo de ventana preferido"
	L["Minimized Standalone"] = "Ventana independiente minimizado"
	L["When automatically showing the Rematch window, show the minimized standalone window."] = "Al mostrar automáticamente la ventana Rematch, muestra la ventana independiente minimizada."
	L["Maximized Standalone"] = "Ventana independiente maximizado"
	L["When automatically showing the Rematch window, show the maximized standalone window."] = "Cuando se muestra automáticamente la ventana Rematch, muestra la ventana independiente maximizada."
	L["Pet Journal"] = "Diario de mascotas"
	L["When automatically showing the Rematch window, show the pet journal."] = "Al mostrar automáticamente la ventana de Rematch, muestra el diario de mascotas."
	L["Standalone Window Options"] = "Opciones de ventana independiente"
	L["Use Custom Scale"] = "Usar escala personalizada"
	L["Change the relative size of the standalone window to anywhere between 50% and 200% of its standard size.\n\n\124cffffffffNote:\124r This setting (like the other Standalone Window Options) \124cffffffffdoes not\124r affect the pet journal window."] = "Cambia el tamaño relativo de la ventana independiente a un valor comprendido entre el 50% y el 200% de su tamaño estándar.\n\n\124cffffffffNota:\124r Esta configuración (al igual que las demás opciones de ventanas independientes) \124cffffffffdoes not\124r afectan a la ventana del diario de mascotas."
	L["Single Panel Mode"] = "Modo de panel único"
	L["Collapse the maximized standalone window to one panel instead of two side by side.\n\nUsers of earlier versions of Rematch may find this mode more familiar."] = "Contrae la ventana independiente maximizada en un panel en lugar de dos uno al lado del otro.\n\nLos usuarios de versiones anteriores de Rematch pueden encontrar este modo más familiar."
	L["Combine Pets And Queue"] = "Combinar mascotas y cola"
	L["In single panel mode, combine the Pets and Queue tabs together. A narrow queue will display to the right of the pet list instead of in a separate tab."] = "En el modo de panel único, combina las pestañas Mascotas y Cola. Se mostrará una cola estrecha a la derecha de la lista de mascotas en lugar de en una pestaña separada."
	L["Keep Window On Screen"] = "Mantener ventana en pantalla"
	L["Don't hide the standalone window when the ESCape key is pressed or most other times it would hide, such as going to the game menu."] = "No oculta la ventana independiente cuando se pulsa la tecla ESC o la mayoría de los otros momentos en que se ocultaría, como ir al menú del juego."
	L["Even For Pet Battles"] = "Incluso para duelos de mascotas"
	L["Keep the standalone window on the screen even when you enter pet battles."] = "Mantener la ventana independiente en la pantalla incluso cuando entres en duelos de mascotas."
	L["Even Across Sessions"] = "Incluso entre sesiones"
	L["If the standalone window was on screen when logging out, automatically summon it on next login."] = "Si la ventana independiente estaba en pantalla al cerrar la sesión, se invoca automáticamente en el siguiente inicio de sesión."
	L["Don't Minimize With ESC Key"] = "No minimizar con la tecla ESC"
	L["Don't minimize the standalone window when the ESCape key is pressed."] = "No minimiza la ventana independiente cuando se pulsa la tecla ESC."
	L["Or With Panel Tabs"] = "O con panel de pestañas"
	L["Don't let the Pets, Teams, Queue or Options tabs minimize the standalone window."] = "No permite que las pestañas Mascotas, Equipos, Cola u Opciones minimicen la ventana independiente."
	L["Lower Window Behind UI"] = "Ventana inferior detrás de la UI"
	L["Push the standalone window back behind other parts of the UI so other parts of the UI can appear ontop."] = "Empuja la ventana independiente detrás de otras partes de la interfaz de usuario para que otras partes de la interfaz de usuario puedan aparecer en la parte superior."
	L["Move Panel Tabs To Right"] = "Mover el panel de pestañas a la derecha"
	L["Align the Pets, Teams, Queue and Options tabs to the right side of the standalone window."] = "Alinea las pestañas Mascotas, Equipos, Cola y Opciones al lado derecho de la ventana independiente."
	L["Appearance Options"] = "Opciones de apariencia"
	L["Compact List Format"] = "Formato de lista compacta"
	L["Use an alternate style of lists for Pets, Teams, Queue and Targets to display more on the screen at once."] = "Usar un estilo alternativo de listas para Mascotas, Equipos, Cola y Objetivos para mostrar más en la pantalla a la vez."
	L["Use Smaller Text Too"] = "Usar texto más pequeño también"
	L["Also use smaller text in the Compact List Format so more text displays on each button."] = "Utiliza también texto más pequeño en el formato de lista compacta para que aparezca más texto en cada botón."
	L["Color Pet Names By Rarity"] = "Nombres de mascotas por color según su rareza"
	L["Make the names of pets you own the same color as its rarity. Blue for rare, green for uncommon, etc."] = "Hace que los nombres de las mascotas que posees sean del mismo color que su rareza. Azul para raro, verde para poco común, etc."
	L["Hide Rarity Borders"] = "Ocultar bordes de rareza"
	L["Don't color the icon border for pets you own in the same color as its rarity."] = "No colorea el borde del icono de tus mascotas del mismo color que su rareza."
	L["Hide Level At Max Level"] = "Ocultar nivel en el nivel máximo"
	L["If a pet is level 25, don't show its level on the pet icon."] = "Si una mascota tiene el nivel 25, no muestra su nivel en el icono de la mascota."
	L["Show Ability Numbers"] = "Mostrar números de habilidad"
	L["In the ability flyout, show the numbers 1 and 2 to help with the common notation such as \"Pet Name 122\" to know which abilities to use."] = "En el desplegable de habilidades, muestra los números 1 y 2 para ayudar con la notación común como \"Pet Name 122\" para saber qué habilidades utilizar."
	L["On Loaded Abilities Too"] = "También en las habilidades cargadas"
	L["In addition to the flyouts, show the numbers 1 and 2 on loaded abilities."] = "Además de los volantes, muestra los números 1 y 2 en habilidades cargadas."
	L["Show Breeds As Text Not Icons"] = "Mostrar razas como texto, no como íconos"
	L["Rather than use icons for PetTracker's breeds, display breeds in the more standard letter format such as B/B, H/P, etc.\n\n\124cffffffffNote:\124r This option only supports the later versions of PetTracker. Older PetTracker versions are not supported."] = "En lugar de utilizar iconos para las razas de PetTracker, muestra las razas en el formato de letra más estándar, como B/B, H/P, etc.\n\n\124cffffffffNote:\124r Esta opción sólo es compatible con las últimas versiones de PetTracker. Las versiones anteriores de PetTracker no son compatibles."
	L["List Behavior Options"] = "Lista de opciones de comportamiento"
	L["Slow Mousewheel Scroll"] = "Desplazamiento lento de la rueda del ratón"
	L["In the Pets, Teams, Queue, Target and Options lists, mousewheel over the list will scroll one line at a time instead of a whole page at a time.\n\nYou can still scroll by pages by clicking above or below the scroll thumb."] = "En las listas de Mascotas, Equipos, Cola, Destino y Opciones, al pasar el ratón por encima de la lista se desplazará una línea cada vez en lugar de una página entera cada vez.\n\nPuede seguir desplazándote por las páginas haciendo click encima o debajo del pulgar de desplazamiento."
	L["Remember Expanded Lists"] = "Recordar listas expandidas"
	L["In lists that can expand and collapse, such as Options or Targets, remember what was expanded when logging out or reloading; rather than starting with collapsed lists on login."] = "En las listas que se pueden expandir y colapsar, como Opciones u Objetivos, recuerda lo que se expandió al cerrar la sesión o recargar; en lugar de comenzar con listas colapsadas al iniciar sesión."
	L["Collapse Lists With ESC Key"] = "Colapsar listas con la tecla ESC"
	L["When a list that can expand or collapse is on screen, such as Options or Targets, make the ESCape key collapse the list if any part is expanded."] = "Cuando una lista que puede expandirse o colapsarse está en pantalla, como Opciones u Objetivos, hace que la tecla ESC colapse la lista si alguna parte está expandida."
	L["Toolbar Options"] = "Opciones de la barra de herramientas"
	L["Move Toolbar To Bottom"] = "Mover barra de herramientas a la parte inferior"
	L["Move the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc) to the bottom of the standalone window.\n\nAlso convert the red panel buttons (Save, Save As, Find Battle) to toolbar buttons."] = "Mueve los botones de la barra de herramientas (revivir mascotas, vendas, sombrero safari, etc.) a la parte inferior de la ventana independiente.\n\nConvierte también los botones del panel rojo (Guardar, Guardar como, Buscar batalla) en botones de la barra de herramientas."
	L["Reverse Toolbar Buttons"] = "Invertir botones de la barra de herramientas"
	L["Reverse the order of the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc)."] = "Invierte el orden de los botones de la barra de herramientas (Revivir mascotas de batalla, Vendas para mascotas de batalla, Sombrero safari, etc.)."
	L["Hide On Toolbar Right Click"] = "Ocultar en barra de herramientas click derecho"
	L["When a toolbar button is used with a right click, dismiss the Rematch window after performing its action."] = "Cuando se utiliza un botón de la barra de herramientas con el botón derecho del ratón, se cierra la ventana Rematch después de realizar su acción."
	L["Safari Hat Reminder"] = "Recordatorio del sombrero de Safari"
	L["Draw attention to the safari hat button while a pet below max level is loaded.\n\nAlso show the Rematch window when a low level pet loads and the safari hat is not equipped."] = "Llama la atención sobre el botón del sombrero safari mientras se carga una mascota por debajo del nivel máximo.\n\nTambién muestra la ventana de Rematch cuando se carga una mascota de bajo nivel y el sombrero de safari no está equipado."
	L["Show Import Button"] = "Mostrar botón de importación"
	L["Add a button to the toolar to import a single team or many teams exported from Rematch."] = "Agregue un botón a la barra de herramientas para importar un solo equipo o muchos equipos exportados de Rematch."
	L["Pet Card & Notes Options"] = "Opciones de tarjetas y notas para mascotas"
	L["Allow Pet Cards To Be Pinned"] = "Permitir que las tarjetas de mascotas se anclen"
	L["When dragging a pet card to another part of the screen, pin the card so all future pet cards display in the same spot, until the pet card is moved again or the unpin button is clicked."] = "Cuando arrastres una tarjeta de mascota a otra parte de la pantalla, ancle la tarjeta para que todas las futuras tarjetas de mascota se muestren en el mismo lugar, hasta que la tarjeta de mascota se mueva de nuevo o se pulse el botón de desanclar."
	L["Click For Pet Cards & Notes"] = "Click para tarjetas y notas de mascotas"
	L["Instead of automatically showing pet cards and notes when you mouseover them, require clicking the pet or notes button to display them."] = "En lugar de mostrar automáticamente las tarjetas de mascotas y las notas al pasar el ratón por encima de ellas, es necesario hacer click en el botón de la mascota o de las notas para mostrarlas."
	L["Faster Pet Cards & Notes"] = "Tarjetas y notas para mascotas más rápidas"
	L["Instead of a small delay before showing pet cards and notes, immediately show them as you mouseover pets and notes buttons."] = "En lugar de un pequeño retraso antes de mostrar las tarjetas de mascotas y las notas, muéstrelas inmediatamente al pasar el ratón por encima de los botones de mascotas y notas."
	L["Use Pet Cards In Battle"] = "Usar tarjetas de mascota en combate"
	L["Use the pet card on the unit frames during a pet battle instead of the default tooltip."] = "Utiliza la tarjeta de mascota en los cuadros de unidad durante una batalla de mascotas en lugar de la información sobre herramientas predeterminada."
	L["Use Pet Cards For Links"] = "Usar tarjetas de mascota para enlaces"
	L["Use the pet card when viewing a link of a pet someone else sent you instead of the default link."] = "Usa la tarjeta de mascota cuando vea un enlace de una mascota que otra persona te envió en lugar del enlace predeterminado."
	L["Keep Notes On Screen"] = "Mantener notas en pantalla"
	L["Don't hide notes when the ESCape key is pressed or other times it would hide, such as changing tabs or closing Rematch."] = "No oculta las notas cuando se presiona la tecla ESC o en otras ocasiones en las que se ocultaría, como al cambiar de pestaña o al cerrar Rematch."
	L["Show Notes Upon Targeting"] = "Mostrar notas tras la selección"
	L["When your target has a saved team with notes, automatically display and lock the notes."] = "Cuando tu objetivo tiene un equipo guardado con notas, muestra y bloquea automáticamente las notas."
	L["Show Notes In Battle"] = "Mostrar notas en batalla"
	L["If the loaded team has notes, display and lock the notes when you enter a pet battle."] = "Si el equipo cargado tiene notas, muestra y bloquea las notas cuando entras en un duelo de mascotas."
	L["Only Once Per Team"] = "Solo una vez por equipo"
	L["Only display notes automatically the first time entering battle, until another team is loaded."] = "Solo muestra las notas automáticamente la primera vez que ingresas a la batalla, hasta que se cargue otro equipo."
	L["Alternate Lore Font"] = "Fuente alternativa de lore"
	L["Use a more normal-looking font for lore text on the back of the pet card."] = "Utilizar un tipo de letra más normal para el texto del reverso de la tarjeta de mascota."
	L["Show Species ID & Ability ID"] = "Mostrar ID de especie e ID de habilidad"
	L["Display the numerical species ID of a pet as a stat on their pet card and the numerical ability ID on ability tooltips."] = "Muestra el ID numérico de especie de una mascota como una estadística en su ficha de mascota y el ID numérico de habilidad en las descripciones emergentes de habilidad."
	L["Hide Notes Buttons In Battle UI"] = "Ocultar botones de notas en la interfaz de batalla"
	L["Hide the notes buttons on the upper corners of the pets in the battle UI when the pet they're attached to has notes."] = "Oculta los botones de notas en las esquinas superiores de las mascotas en la interfaz de batalla cuando la mascota a la que están unidos tiene notas."
	L["Team Options"] = "Opciones de equipo"
	L["Load Healthiest Pets"] = "Cargar mascotas más saludables"
	L["When a team loads, if any pet is injured or dead and there's another version with more health \124cffffffffand identical stats\124r, load the healthier version.\n\nPets in the leveling queue are exempt from this option.\n\n\124cffffffffNote:\124r This is only when a team loads. It will not automatically swap in healthier pets when you leave battle."] = nil
	L["Allow Any Version"] = "Permitir cualquier versión"
	L["Instead of choosing only the healthiest pet with identical stats, choose the healthiest version of the pet regardless of stats."] = "En lugar de elegir sólo la mascota más sana con estadísticas idénticas, elige la versión más sana de la mascota independientemente de las estadísticas."
	L["After Pet Battles Too"] = "Después de las batallas también"
	L["Also load healthiest pets after leaving a pet battle or using a Revive or Bandage within Rematch.\n\n\124cffffffffNote:\124r Use of Revive or Bandages outside Rematch will not be noticed.\n\nThis is an experimental option. If you experience problems and want to report them, \124cffffffffPLEASE\124cffffffff mention that this option is enabled!\124r"] = nil
	L["Show Icon For Pets In Teams"] = "Mostrar icono para mascotas en equipos"
	L["When a pet belongs to a team, show an icon beside their name in the pet list and queue."] = "Cuando una mascota pertenece a un equipo, muestra un icono junto a su nombre en la lista de mascotas y en la cola."
	L["Hide Targets Below Teams"] = "Ocultar objetivos debajo de los equipos"
	L["Hide the target name that appears beneath a team that is not named the same as its target."] = "Oculta el nombre del objetivo que aparece debajo de un equipo que no tiene el mismo nombre que tu objetivo."
	L["Always Show Team Tabs"] = "Mostrar siempre las pestañas de equipo"
	L["Show team tabs along the right side of the window even if you're not on the team panel."] = "Muestra la pestaña de equipo en la parte derecha de la ventana aunque no estés en el panel de equipo."
	L["Move Team Tabs To Left"] = "Mover pestañas de equipo a la izquierda"
	L["Move the team tabs along the right side of the standalone window to the left side."] = "Mueve las pestañas de equipo de la parte derecha de la ventana independiente a la parte izquierda."
	L["Import Team Tabs Too"] = "Importar pestañas de equipo también"
	L["When importing teams created from a 'Backup All Teams' export, teams will import into tabs they were in when backed up.\n\nIf new tabs need to be created, they will have the default icon and options. \n\nAlso, the max number of team tabs is 32. Teams in any tabs that exceed this limit will go to the originally chosen tab.\n\n\124cffffffffNote:\124r This is an \124cffffffffexperimental\124r feature. Your teams won't get deleted from this, but in the event they disappear into random tabs, backup your WTF folder to do a complete restore."] = nil
	L["Share In Legacy Format"] = "Compartir en formato heredado"
	L["When exporting teams or sending to another Rematch user, use the old format.\n\nUse this option when sharing teams with someone on an older Rematch that's unable to import or receive newer teams."] = "Al exportar equipos o enviar a otro usuario de Rematch, usa el formato anterior.\n\nUtiliza esta opción cuando compartas equipos con alguien con una versión de Rematch antigua que no pueda importar o recibir equipos nuevos."
	L["Prioritize Breed On Import"] = "Priorizar la raza en la importación"
	L["When importing or receiving teams, fill the team with the best matched breed as the first priority instead of the highest level."] = "Al importar o recibir equipos, llenar el equipo con la mejor raza compatible como primera prioridad en lugar del nivel más alto."
	L["Randomize Abilities Too"] = "Habilidades aleatorias también"
	L["For random pets, randomize the pets' abilities also."] = "Para las mascotas aleatorias, aleatoriza también las habilidades de las mascotas."
	L["Allow Random Pets From Teams"] = "Permitir mascotas aleatorias de los equipos"
	L["The default behavior for a random pet slot is to not choose a random pet saved in another team, unless all three pet slots are random.\n\nEnable this option to always allow pets from other teams to be included in the random pool."] = "El comportamiento predeterminado para una ranura de mascota aleatoria es no elegir una mascota aleatoria guardada en otro equipo, a menos que las tres ranuras de mascota sean aleatorias.\n\nActiva esta opción para permitir siempre que las mascotas de otros equipos se incluyan en el grupo aleatorio."
	L["Team Win Record Options"] = "Opciones de registro de victorias del equipo"
	L["Auto Track Win Record"] = "Seguimiento automático de récords de victorias"
	L["At the end of each battle, automatically record whether the loaded team won or lost.\n\nForfeits always count as a loss.\n\nYou can still manually update a team's win record at any time."] = "Al final de cada batalla, registra automáticamente si el equipo cargado ganó o perdió.\n\nLas derrotas siempre cuentan como pérdidas.\n\nPuedes seguir actualizando manualmente el récord de victorias de un equipo en cualquier momento."
	L["For PVP Battles Only"] = "Solo para batallas PVP"
	L["Automatically track whether the loaded team won or lost only in a PVP battle and never for a PVE battle."] = "Rastrea automáticamente si el equipo cargado ganó o perdió sólo en una batalla PVP y nunca para una batalla PVE."
	L["Display Total Wins Instead"] = "Mostrar el total de victorias"
	L["Instead of displaying the win percentage of a team on the win record button, display the total number of wins.\n\nTeam tabs that are sorted by win record will sort by total wins also."] = "En lugar de mostrar el porcentaje de victorias de un equipo en el botón de registro de victorias, muestra el número total de victorias.\n\nLas pestañas de equipo ordenadas por récord de victorias también se ordenarán por total de victorias."
	L["Hide Win Record Buttons"] = "Ocultar botones de registro de victorias"
	L["Hide the win record button displayed to the right of each team.\n\nYou can still manually edit a team's win record from its right-click menu and automatic tracking will continue if enabled."] = "Oculta el botón de registro de victorias que se muestra a la derecha de cada equipo.\n\nPuedes seguir editando manualmente el récord de victorias de un equipo desde su menú contextual y el seguimiento automático continuará si está activado."
	L["Leveling Queue Options"] = "Opciones de la cola de nivelación"
	L["Prefer Living Pets"] = "Preferir mascotas vivas"
	L["When loading pets from the queue, skip dead pets and load living ones first."] = "Al cargar mascotas desde la cola, omite las mascotas muertas y carga primero las vivas."
	L["And At Full Health"] = "Y con salud plena"
	L["Also prefer uninjured pets when loading pets from the queue."] = "También prefiere mascotas no heridas al cargar mascotas de la cola."
	L["Double Click To Send To Top"] = "Doble click para enviar a la parte superior"
	L["When a pet in the queue panel is double clicked, send it to the top of the queue instead of summoning it."] = "Cuando se hace doble click en una mascota del panel de cola, se envía a la parte superior de la cola en lugar de invocarla."
	L["Hide Leveling Pet Toast"] = "Ocultar logro para mascotas de nivelación"
	L["Don't display the popup 'toast' when a new pet is automatically loaded from the leveling queue."] = "No mostrar la ventana de logro cuando una nueva mascota se cargue automáticamente desde la cola de nivelación."
	L["Automatically Level New Pets"] = "Nivelar automáticamente nuevas mascotas"
	L["When you capture or learn a pet, automatically add it to the leveling queue."] = "Cuando captures o aprendas una mascota, agregarla automáticamente a la cola de nivelación."
	L["Only Pets Without A 25"] = "Sólo mascotas sin un ejemplar en 25"
	L["Only automatically level pets which don't have a version already at 25 or in the queue."] = "Sólo subir automáticamente de nivel a las mascotas que no tengan una versión ya a 25 o en cola."
	L["Only Rare Pets"] = "Solo mascotas de calidad rara"
	L["Only automatically level rare quality pets."] = "Solo nivelar automáticamente mascotas de calidad rara."
	L["Random Pet When Queue Empty"] = "Mascota aleatoria cuando la cola está vacía"
	L["When the queue is empty, load a random high-level pet in any leveling slots."] = "Cuando la cola esté vacía, se cargará una mascota aleatoria de alto nivel en cualquier ranura de nivelación."
	L["Pet Filter Options"] = "Opciones de filtro de mascotas"
	L["Use Level In Strong Vs Filter"] = "Usar filtro nivel fuerte VS"
	L["When doing a Strong Vs filter, take the level of the pet into account. If a pet is not high enough level to use a Strong Vs ability, do not list the pet.\n\n\124cffffffffNote:\124r A Strong Vs filter is sometimes useful for identifying pets you want to level or capture. This option will hide those pets while the Strong Vs filter is active."] = "Al hacer un filtro Strong Vs, tiene en cuenta el nivel de la mascota. Si una mascota no tiene un nivel lo suficientemente alto como para usar una habilidad Strong Vs, no incluye la mascota.\n\n\124cffffffffNota:\124r Un filtro Strong Vs a veces es útil para identificar las mascotas que deseas nivelar o capturar. Esta opción ocultará esas mascotas mientras el filtro Strong Vs esté activo."
	L["Reset Filters On Login"] = "Restablecer filtros al iniciar sesión"
	L["When logging in, start with all pets listed and no filters active."] = "Al iniciar sesión, comienzas con todas las mascotas en la lista y sin filtros activos."
	L["Reset Sort With Filters"] = "Restablecer ordenación con filtros"
	L["When clearing filters, also reset the sort back to the default: Sort by Name, Favorites First."] = "Al borrar los filtros, también restablece la clasificación a la predeterminada: Ordenar por nombre, Favoritos primero."
	L["Don't Reset Search With Filters"] = "No restablecer la búsqueda con filtros"
	L["When manually clearing filters, don't clear the search box too.\n\nSome actions, such as logging in or Find Similar, will always clear search regardless of this setting."] = "Cuando borras manualmente los filtros, no borras también el cuadro de búsqueda.\n\nAlgunas acciones, como iniciar sesión o Buscar similares, siempre borrarán la búsqueda independientemente de esta configuración."
	L["Sort By Chosen Name"] = "Ordenar por nombre elegido"
	L["When pets are sorted by name, sort them by the name given with the Rename option instead of their original name."] = "Cuando las mascotas se ordenan por nombre, se ordenan por el nombre dado con la opción Renombrar en lugar de por su nombre original."
	L["Don't Sort By Relevance"] = "No ordenar por relevancia"
	L["When searching for something by name in the search box, do not sort the results by relevance.\n\nWhen sorted by relevance, pets with the search term in their name are listed first, followed by terms in notes, then abilities and then source text last."] = "Cuando busquea algo por su nombre en el cuadro de búsqueda, no ordena los resultados por relevancia.\n\nCuando se ordenan por relevancia, las mascotas con el término de búsqueda en su nombre aparecen en primer lugar, seguidas de los términos en las notas, luego las habilidades y por último el origen."
	L["Hide Non-Battle Pets"] = "Ocultar mascotas que no pueden luchar"
	L["Only list pets that can battle. Do not list pets like balloons, squires and other companion pets that cannot battle."] = "Enumera sólo mascotas que puedan combatir. No incluye mascotas como globos, escuderos y otras mascotas de compañía que no pueden luchar."
	L["Allow Hidden Pets"] = "Permitir mascotas ocultas"
	L["Allow the ability to hide specific pet species in the pet list with a 'Hide Pet' in the list's right-click menu.\n\nYou can view pets you've hidden from the Other -> Hidden Pets filter."] = ""
	L["Confirmation Options"] = "Opciones de confirmación"
	L["Don't display a popup when a team loads and a pet within the team can't be found."] = "No mostrar una ventana emergente cuando se carga un equipo y no se puede encontrar una mascota dentro del equipo."
	L["Don't ask for confirmation when hiding a pet.\n\nYou can view hidden pets in the 'Other' pet filter."] = "No pedir confirmación cuando escondas una mascota.\n\nPuedes ver las mascotas ocultas en el filtro de mascotas 'Otras'."
	L["Don't Remind About Backups"] = "No recordar acerca de las copias de seguridad"
	L["Don't show a popup offering to backup teams every once in a while. Generally, the popup appears sometime after the number of teams increases by 50."] = "No mostrar una ventana emergente ofreciendo hacer copias de seguridad de los equipos de vez en cuando. Generalmente aparece en algún momento después de que el número de equipos supera los 50."
	L["Don't Ask When Caging Pets"] = "No preguntar al enjaular mascotas"
	L["Don't ask for confirmation when putting a pet in a cage."] = "No pedir confirmación al enjaular una mascota."
	L["Don't Confirm To Fill Queue"] = "No confirmar para llenar la cola"
	L["Don't ask for confirmation when using the 'Fill Queue' or 'Fill Queue More' menu items in the Queue menu."] = "No pedir confirmación cuando se use los elementos de menú 'Llenar cola' o 'Llenar más cola' en el menú Cola."
	L["Miscellaneous Options"] = "Opciones varias"
	L["Show After Pet Battle"] = "Mostrar después de un duelo de mascotas"
	L["Show the Rematch window after leaving a pet battle."] = "Muestra la ventana de Rematch después de abandonar un duelo de mascotas."
	L["But Not After PVP Battle"] = "Pero no después de la batalla PVP"
	L["Since pets don't remain injured in PVP battles, don't show the window when leaving a PVP battle."] = "Dado que las mascotas no quedan heridas en las batallas de PVP, no muestra la ventana al salir de una batalla PVP."
	L["Disable Sharing"] = "Desactivar Compartir"
	L["Disable the Send button and also block any incoming pets sent by others. Import and Export still work."] = "Desactiva el botón Enviar y bloquea también las mascotas entrantes enviadas por otros. Importar y Exportar siguen funcionando."
	L["Use Minimap Button"] = "Usar el botón del minimapa"
	L["Place a button on the minimap to toggle Rematch and load favorite teams."] = "Colocar un botón en el minimapa para activar Rematch y cargar los equipos favoritos."
	L["Keep Companion"] = "Mantener compañero"
	L["After a team is loaded, summon back the companion that was at your side before the load; or dismiss the pet if you had none summoned."] = "Después de cargar un equipo, vuelve a invocar al compañero que estaba a tu lado antes de la carga; o despide a la mascota si no tenías ninguna invocada."
	L["No Summon On Double Click"] = "No invocar al hacer doble click"
	L["Do nothing when pets within Rematch are double-clicked. The normal behavior of double click throughout Rematch is to summon or dismiss the pet."] = "No hacer nada cuando se haga doble click en las mascotas usando Rematch. El comportamiento normal del doble click con Rematch es invocar o retirar la mascota."
	L["Hide Tooltips"] = "Ocultar información sobre herramientas"
	L["Hide the more common tooltips in Rematch."] = "Oculta la información sobre herramientas más común en Rematch."
	L["Hide Extra Help"] = "Ocultar ayuda extra"
	L["Hide the informational \"Help\" items found in many menus and on the pet card."] = "cultar los elementos informativos \"Ayuda\" que se encuentran en muchos menús y en la tarjeta de mascota."
	L["Use Default Pet Journal"] = "Usar el diario de mascotas predeterminado"
	L["Turn off Rematch integration with the default pet journal.\n\nYou can still use Rematch in its standalone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "Desactiva la integración de Rematch con el diario de mascotas predeterminado.\n\nPuedes seguir utilizando Rematch en su ventana independiente, a la que se accede mediante la vinculación de teclas, el comando /rematch o desde el botón Minimapa si está activado en las opciones."
	L["Debugging Options"] = "Opciones de depuración"
	L["Debug: Journal FrameLevel"] = "Depuración: nivel de marco de diario"
	L["Check this to less aggressively try to take over the default pet journal. Specifically, it will give up sooner if it can't raise frame level above all other addons' frames in the journal."] = "Marca esta opción para intentar tomar el control del diario de mascotas por defecto de forma menos agresiva. En concreto, se rendirá antes si no puede aumentar el nivel de fotogramas por encima de los fotogramas de todos los demás complementos en el diario."
	L["Debug: No Cache"] = "Depuración: sin caché"
	L["Check this to disable the automatic caching of NPC names when the addon launches.\n\n\124cffffffffNote:\124r If a target's name appears as something like 'NPC 1234' while this option is enabled, it's probably because of this option. It should correct itself on its own over time."] = "Marca esta opción para desactivar el almacenamiento automático de los nombres de los NPCS cuando se inicia el addon.\n\n\124cffffffffNota:\124r Si el nombre de un objetivo aparece como 'NPC 1234' mientras esta opción está activada, probablemente se deba a esta opción. Debería corregirse por sí solo con el tiempo."
	L["Debug: No Sanctuary"] = "Depuración: Sin santuario"
	L["Check this to disable the 'Sanctuary' system that acts as a safety net for server petID reassignments.\n\n\124cffffffffNote:\124r While this option is enabled, any pets in teams will become greyed out if their petID changes. When the team loads, an arbitrary one of the same species will be loaded in its place.\n\n\124cffff4040WARNING!\124r While this option is enabled, make frequent backups of your teams with the 'Backup All Teams' options in the Teams button at the top of the Teams Tab."] = "Marque esta opción para desactivar el sistema 'Santuario' que actúa como red de seguridad para las reasignaciones de petID del servidor.\n\n\124cffffffffNota:\124r Mientras esta opción esté activada, las mascotas de los equipos aparecerán en gris si su petID cambia. Cuando se cargue el equipo, se cargará uno arbitrario de la misma especie en su lugar.\n\n\124cffff4040¡ADVERTENCIA!\124r Mientras esta opción esté habilitada, realice copias de seguridad frecuentes de sus equipos con las opciones 'Copia de seguridad de todos los equipos' en el botón Equipos en la parte superior de la pestaña Equipos."
	L["Debug: Delay Journal"] = "Depuración: retraso del diario"
	L["Delay Rematch taking over the journal on the first launch by a full second."] = "Retrasa que Rematch se haga cargo del diario en el primer lanzamiento por un segundo completo."
	L["Delay Just One Frame"] = "Retrasar sólo un fotograma"
	L["Change the delay from half a second to one frame, or nearly instant."] = "Cambia el retraso de medio segundo a un fotograma, o casi instantáneo."
	L["Debug: No Models"] = "Depuración: No hay modelos"
	L["Prevent the creation or rendering of any models within Rematch. This includes the target panel, loadout slots and pet card.\n\n\124cffff4040This option requires a Reload."] = "Evita la creación o renderización de cualquier modelo dentro de Rematch. Esto incluye el panel de objetivos, las ranuras de carga y la tarjeta de mascota.\n\n\124cffff4040Esta opción requiere /reload."
	L["Rematch version %s"] = "Versión de Rematch: %s"
	L["The%s icon marks new options."] = "El icono%s marca nuevas opciones."

-- Panels\TargetPanel.lua
	L["Search Targets"] = "Buscar objetivos"
	L["All Targets"] = "Todos los objetivos"
	L["Targets with a \124TInterface\\AddOns\\Rematch\\Textures\\hasteam:18\124t have a saved team."] = "Los objetivos con un \124TInterface\\AddOns\\Rematch\\Textures\\hasteam:18\124t tienen un equipo guardado."

-- Widgets\BottomPanel.lua
	L["You can also double-click a pet to summon or dismiss it."] = "También puedes hacer doble click en una mascota para invocarla o retirarla."
	L["Disable Rematch"] = "Desactivar Rematch"
	L["Uncheck this to restore the default pet journal.\n\nYou can still use Rematch in its standlone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "Desmarca esto para volver al diario de mascotas predeterminado.\n\nAún puedes usar Rematch en su ventana independiente, a la que se accede a través de combinación de teclas, comando /rematch o desde el botón en el minimapa si está habilitado en las opciones."

-- Widgets\TeamTabs.lua
	L["Edit Tab"] = "Editar pestaña"
	L["Change the name or icon of this tab."] = "Cambia el nombre o el icono de esta pestaña."
	L["Custom Sort"] = "Orden personalizado"
	L["Remove Custom Sort"] = "Eliminar orden personalizado"
	L["Are you sure you want to remove the custom sort order?\n\nThe saved order of teams will be lost and turning this option back on will not restore the old order."] = "¿Estás seguro de que deseas eliminar el orden de clasificación personalizado?\n\nEl orden guardado de los equipos se perderá y volver a activar esta opción no restaurará el orden anterior."
	L["While checked, you can rearrange the order of teams within this tab from the teams' right-click menu."] = "Mientras está marcado, puede reorganizar el orden de los equipos dentro de esta pestaña desde el menú del botón derecho del equipo."
	L["Sort By Wins"] = "Ordenar por victorias"
	L["This option is disabled while Custom Sort is active."] = "Esta opción está desactivada mientras el orden personalizado está activo."
	L["Sort teams in this tab by their wins.\n\nFavorited teams will still list at the top."] = "Ordenar los equipos en esta pestaña por sus victorias.\n\nLos equipos favoritos seguirán apareciendo en la parte superior."
	L["Set leveling preferences for all teams within this tab.\n\nIf a team within this tab also has preferences, the tab's preferences will take priority over the team's preferences."] = "Configurar las preferencias de nivelación para todos los equipos dentro de esta pestaña.\n\nSi un equipo dentro de esta pestaña también tiene preferencias, las preferencias de la pestaña tendrán prioridad sobre las preferencias del equipo."
	L["Export Tab"] = "Exportar pestaña"
	L["Export all teams in this tab to a string you can copy elsewhere, such as forums or emails.\n\nOther Rematch users can then paste these teams into their Rematch via Import Teams.\n\nYou can export a single team by right-clicking one and choosing its Share menu."] = "Exporta todos los equipos de esta pestaña a una cadena que puedes copiar en otro lugar, como foros o correos electrónicos.\n\nOtros usuarios de Rematch pueden entonces pegar estos equipos en su Rematch a través de Importar Equipos.\n\nPuedes exportar un solo equipo haciendo click con el botón derecho del ratón en uno de ellos y seleccionando el menú Compartir."
	L["Delete Tab"] = "Borrar pestaña"
	L["Delete this tab and move all of its teams to the default tab."] = "Borre esta pestaña y mueva todos sus equipos a la pestaña predeterminada."
	L["Delete Teams"] = "Borrar equipos"
	L["Permanently delete all teams in this tab."] = "Eliminar permanentemente todos los equipos de esta pestaña."
	L["Previous Tabs"] = "Pestañas anteriores"
	L["Next Tabs"] = "Siguientes pestañas"
	L["Create New Tab"] = "Crear nueva pestaña"
	L["Teams: %d"] = "Equipos: %d"
	L["New Tab"] = "Nueva pestaña"
	L["Choose a name and icon"] = "Elige un nombre y un icono"
	L["Search Icons"] = "Buscar iconos"
	L["Delete Teams?"] = "¿Borrar equipos?"
	L["Delete ALL teams in the first tab?"] = "¿Borrar TODOS los equipos de la primera pestaña?"
	L["%sWARNING!\124r This will %sPERMANENTLY DELETE\124r all teams in this tab!"] = "%s¡ADVERTENCIA!\124r Esta acción %sBORRARA PERMANENTEMENTE\124r todos los equipos en esta pestaña!"
	L["Delete this tab?"] = "¿Borrar esta pestaña?"
	L["Deleting this tab will move its teams to the %s tab."] = "Eliminar esta pestaña moverá sus equipos a la pestaña %s."
	L["Delete teams within the tab too"] = "Eliminar equipos dentro de la pestaña también"

-- Widgets\TeamTabIcons.lua

-- Widgets\LoadedTeamPanel.lua
	L["Reload Team"] = "Volver a cargar equipo"
	L["When a team is loaded its name goes here. You can reload the team by clicking here or right-click for team options such as setting notes."] = "Cuando se carga un equipo, su nombre va aquí. Puede volver a cargar el equipo haciendo clic aquí o haciendo clic con el botón derecho para ver las opciones del equipo, como las notas de configuración."
	L["Last Loaded Team"] = "Último equipo cargado"

-- Dialogs\Save.lua
	L["Target For This Team"] = "Objetivo para este equipo"
	L["A target stored in a team is used to decide which team to load when you return to that target.\n\nYou can save an unlimited number of teams to fight a target, but a target can only be saved in one team."] = "Un objetivo almacenado en un equipo se usa para decidir qué equipo cargar cuando regresas a ese objetivo.\n\nPuedes guardar una cantidad ilimitada de equipos para luchar contra un objetivo, pero un objetivo solo se puede guardar en un equipo."
	L["Name:"] = "Nombre"
	L["Target:"] = "Objetivo:"
	L["Save As.."] = "Guardar como..."
	L["Save this team?"] = "¿Guardar este equipo?"
	L["Save Notes & Preferences Too"] = "Guardar notas y preferencias también"
	L["All teams must have a name."] = "Todos los equipos deben tener un nombre."
	L["This target already has a team."] = "Este objetivo ya tiene un equipo."
	L["A team already has this name."] = "Un equipo ya tiene este nombre."
	L["Overwrite Team"] = "Sobrescribir equipo"
	L["Overwrite this team?"] = "¿Sobrescribir este equipo?"
	L["The target %s%s\124r already has a team.\n\nA target can only have one team."] = "El objetivo %s%s\124r ya tiene un equipo.\n\nUn objetivo solo puede tener un equipo."
	L["A team named %s%s\124r already exists.\n\nTeams without a target must have a unique name."] = "Ya existe un equipo llamado %s%s\124r.\n\nLos equipos sin objetivo deben tener un nombre único."

-- Dialogs\Preferences.lua
	L["Minimum Health"] = "Salud mínima"
	L["This is the minimum health preferred for a leveling pet.\n\nThe queue will prefer leveling pets with at least this much health (adjusted by expected damage taken if any chosen)."] = "Esta es la salud mínima preferida para una mascota de nivelación.\in\La cola preferirá nivelar mascotas con al menos esta cantidad de salud (ajustada por el daño esperado recibido si se elige alguna)"
	L["Minimum Level"] = "Nivel mínimo"
	L["This is the minimum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 4.33 is level 4 with 33% xp towards level 5."] = "Este es el nivel mínimo preferido para una mascota de nivelación.\n\nLos niveles pueden ser cantidades parciales. El nivel 4.33 es el nivel 4 con 33% xp hacia el nivel 5."
	L["Maximum Health"] = "Salud máxima"
	L["This is the maximum health preferred for a leveling pet."] = "Esta es la salud máxima preferida para una mascota de nivelación."
	L["Maximum Level"] = "Nivel máximo"
	L["This is the maximum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 23.45 is level 23 with 45% xp towards level 24."] = "Este es el nivel máximo preferido para una mascota de nivelación.\n\nLos niveles pueden ser cantidades parciales. El nivel 23.45 es el nivel 23 con un 45 % de XP hacia el nivel 24."
	L["Or any"] = "O cualquiera"
	L["Allow low-health Magic and Mechanical pets to ignore the Minimum Health, since their racials allow them to often survive a hit that would ordinarily kill them."] = "Permitir que las mascotas mágicas y mecánicas con poca salud ignoren la salud mínima, ya que sus raciales les permiten sobrevivir a menudo a un golpe que normalmente las mataría."
	L["Expected Damage Taken"] = "Daño esperado recibido"
	L["Tab"] = "Pestaña"
	L["Team Preferences"] = "Preferencias de equipo"
	L["Tab Preferences"] = "Pestaña de preferencias"
	L["  For %s pets: %s%d%s"] = "  Para %s mascotas: %s%d%s"
	L["%s %sTab Preferences"] = "%s %sPestaña de preferencias"
	L["%s%s Preferences Paused"] = "%s%s Preferencias pausadas"
	L["%s Resume Preferences"] = "%s Reanudar preferencias"
	L["%s Pause Preferences"] = "%s pausar preferencias"
	L["Leveling Preferences For %s:"] = "Preferencias de nivelación para %s:"
	L["Expected damage taken"] = "Daño esperado recibido"
	L["The minimum health of pets can be adjusted by the type of damage they are expected to receive."] = "La salud mínima de las mascotas se puede ajustar según el tipo de daño que se espera que reciban."
	L["Damage expected"] = "Daño estimado"
	L["  For %s pets: \124cffffd200%d"] = "  Para %s mascotas: \124cffffd200%d"

-- Dialogs\Sideline.lua
	L["New Team"] = "Nuevo equipo"

-- Dialogs\Share.lua
	L["Press Ctrl+C to copy these teams to the clipboard."] = "Presiona Ctrl + C para copiar estos equipos al portapapeles."
	L["Press Ctrl+C to copy this team to the clipboard."] = "Presiona Ctrl + C para copiar este equipo al portapapeles."
	L["Include Preferences"] = "Incluir preferencias"
	L["Include Notes"] = "Incluir notas"
	L["Press Ctrl+V to paste a team from the clipboard."] = "Presiona Ctrl + V para pegar un equipo desde el portapapeles."
	L["Only Load This Team"] = "Solo cargar este equipo"
	L["This will only load the team and not save it.\n\nThis is for loading teams you do not intend to use more than once, like Family Familiar teams."] = "Esto solo cargará el equipo y no lo guardará.\n\nEsto es para cargar equipos que no tienes la intención de usar más de una vez, como los equipos de Familiar de familia"
	L["This is not a recognizable team."] = "Este no es un equipo reconocible."
	L["An existing team already has this %s."] = "Un equipo existente ya tiene esto %s."
	L["target"] = "objetivo"
	L["name"] = "nombre"
	L["Create a new copy"] = "Crear una nueva copia"
	L["Overwrite existing team"] = "Sobrescribir el equipo existente"
	L["%s%d\124r teams are in this import."] = "%s%d\124r equipos están en esta importación."
	L["%s%d\124r have a name or target already used."] = "%s%d\124r tiene un nombre o un objetivo ya utilizado"
	L["Create new copies"] = "Crear nuevas copias"
	L["Overwrite existing teams"] = "Sobrescribir equipos existentes"
	L["Send"] = "Enviar"
	L["Who do you want to send this team to?"] = "¿A quién quieres enviar este equipo?"
	L["Sending..."] = "Enviando..."
	L["No response. Lag or they don't have Rematch?"] = "No responde. ¿Lag o no tienen Rematch?"
	L["Team successfully received!"] = "¡Equipo recibido con éxito!"
	L["Sending...%d%%"] = "Enviando...%d%%"
	L["They're busy. Try again later."] = "Están ocupados Inténtalo de nuevo más tarde."
	L["They're in combat. Try again later."] = "Están en combate. Inténtalo de nuevo más tarde."
	L["They have team sharing disabled."] = "Tienen equipo para compartir deshabilitado."
	L["Incoming Rematch Team!"] = "¡Equipo de Rematch entrante!"
	L["%s%s\124r has sent you a team named \"%s\" (for %s)."] = "%s%s\124r te ha enviado un equipo llamado \"%s\" (para %s)."
	L["%s%s\124r has sent you a team for %s."] = "%s%s\124r haz enviado un equipo para %s."
	L["%s%s\124r has sent you a team named \"%s\"."] = "%s%s\124r te ha enviado un equipo llamado \"%s\"."
	L["Import these teams?"] = "¿Importar estos equipos?"
	L["Import"] = "Importar"
	L["%s%d\124r Rematch teams have the same name."] = "%s%d\124r equipos de Rematch tienen el mismo nombre."
	L["Note: Teams will be saved in the current team tab, and will not overwrite existing teams. Any name conflicts will add a number to the end of the imported team."] = "Nota: Los equipos se guardarán en la pestaña del equipo actual y no sobrescribirán los equipos existentes. Cualquier conflicto de nombres agregará un número al final del equipo importado."
	L["Please Wait..."] = "Por favor espere..."
	L["Note: These are just your teams and their notes and preferences. Tab information, sort orders, win records and other settings are not included.\n\nFor the most complete backup of all your addon data, please backup your Word of Warcraft\\WTF folder."] = nil
	L["Press Ctrl+C to copy these teams to the clipboard. Then paste them into an email to yourself or a text file someplace safe.\n\nIf you ever need to restore your teams, paste them back in with Import Teams."] = nil
	L["Backup All Rematch Teams?"] = "¿Hacer copia de seguridad de todos los equipos de Rematch?"
	L["You have %s%d\124r Rematch teams.\n\nWould you like to back them up?"] = "You have %s%d\124r equipos en Rematch.\n\n¿¿Te gustaría respaldarlos?"
	L["Choosing Yes will export all teams to copy and paste in an email to yourself or someplace safe.\n\nYou can also do this at any time from the Teams button at the top of the Teams panel of Rematch."] = "Si eliges Sí, exportará todos los equipos para copiar y pegar en un correo electrónico para ti mismo o en un lugar seguro.\n\nTambién puedes hacer esto en cualquier momento desde el botón Equipos en la parte superior del panel Equipos de Rematch."

-- Dialogs\Tooltip.lua

-- Dialogs\ScriptFilter.lua
	L["Pet Variables"] = "Variables de mascotas"
	L["Exposed API"] = "Exponer API"
	L["Test"] = "Prueba"
	L["line "] = "línea"
	L["Pet Filter Script Error"] = "Error de secuencia de comandos de filtro de mascota"
	L["Error in %s"] = "Error en %s"
	L["\124TInterface\\RaidFrame\\ReadyCheck-NotReady:16\124t Error %s"] = nil
	L["\124TInterface\\RaidFrame\\ReadyCheck-Ready:16\124t Script ran without errors!"] = nil
	L["\124cffffd200-\124r Scripts are a way to create custom pet filters.\n\n\124cffffd200-\124r Scripts are Lua code and require some knowledge of the language and API to create your own filters.\n\n\124cffffd200-\124r Scripts run for each pet and should return true if the pet is to be listed.\n\n\124cffffd200-\124r Some variables are filled in as the script runs for each pet. See Pet Variables.\n\n\124cffffd200-\124r Scripts run in a restricted environment with no access outside its environment. See Exposed API.\n\n\124cffffd200-\124r All variables/tables created exist only in this environment and disappear when the filter finishes.\n\n\124cffffd200-\124r If the first line of the script is a --comment, it will be used as a tooltip in the Script menu."] = nil
	L["These variables are defined as the script runs for each pet:\n\n\124cffffd200owned\124r \124cffaaaaaa(boolean)\124r\nWhether the pet is owned by the player.\n\n\124cffffd200petID\124r \124cffaaaaaa(string)\124r\nUnique ID of the owned pet, such as \"BattlePet-0-000004A98F18\".\n\n\124cffffd200speciesID\124r \124cffaaaaaa(number)\124r\nShared ID of the pet's family. Black Tabby Cats are species 42.\n\n\124cffffd200customName\124r \124cffaaaaaa(string)\124r\nName given to the pet by the player.\n\n\124cffffd200level\124r \124cffaaaaaa(number)\124r\nLevel of the pet, or nil for uncollected pets.\n\n\124cffffd200xp\124r \124cffaaaaaa(number)\124r\nAmount of xp the pet has in its current level.\n\n\124cffffd200maxXp\124r \124cffaaaaaa(number)\124r\nTotal amount of xp required to reach the pet's next level.\n\n\124cffffd200displayID\124r \124cffaaaaaa(number)\124r\nA numeric representation of a pet's model skin.\n\n\124cffffd200isFavorite\124r \124cffaaaaaa(boolean)\124r\nWhether the pet is favorited by the player.\n\n\124cffffd200name\124r \124cffaaaaaa(string)\124r\nTrue name of the pet species.\n\n\124cffffd200icon\124r \124cffaaaaaa(string)\124r\nTexture path of the pet's icon.\n\n\124cffffd200petType\124r \124cffaaaaaa(number)\124r\nValue between 1 and 10 for its type. 1=Humanoid, 2=Dragonkin, etc.\n\n\124cffffd200creatureID\124r \124cffaaaaaa(number)\124r\nThe npcID of the pet when it's summoned.\n\n\124cffffd200sourceText\124r \124cffaaaaaa(string)\124r\nFormatted text describing where the pet is from.\n\n\124cffffd200description\124r \124cffaaaaaa(string)\124r\nLore text of the species.\n\n\124cffffd200isWild\124r \124cffaaaaaa(boolean)\124r\nWhether the pet was a captured wild pet.\n\n\124cffffd200canBattle\124r \124cffaaaaaa(boolean)\124r\nWhether the pet can battle.\n\n\124cffffd200tradable\124r \124cffaaaaaa(boolean)\124r\nWhether the pet can be caged.\n\n\124cffffd200unique\124r \124cffaaaaaa(boolean)\124r\nWhether no more than one of the pet can be known at a time.\n\n\124cffffd200abilityList\124r \124cffaaaaaa(table)\124r\nArray of abilityIDs used by the species.\n\n\124cffffd200levelList\124r \124cffaaaaaa(table)\124r\nArray of levels the abilityIDs are learned.\n\nFurther information about pets can be retrieved with the \124cffffd200petInfo\124r system. See Process\\PetInfo.lua for more information."] = nil
	L["The script environment is restricted with access to only common Lua and the following:\n\n\124cffffd200C_PetJournal \124cffaaaaaa(table)\124r\nThe default API for journal functions.\n\n\124cffffd200C_PetBattles \124cffaaaaaa(table)\124r\nThe default API for the battle UI.\n\n\124cffffd200GetBreed \124cffaaaaaa(function)\nArgument:\124r petID\n\124cffaaaaaaReturns:\124r The numeric breed (3-12) of a petID if one of the supported breed addons is enabled.\n\n\124cffffd200GetSource \124cffaaaaaa(function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r The numeric source (1-10) of a speciesID. 1=Drop, 2=Quest, etc.\n\n\124cffffd200IsPetLeveling \124cffaaaaaa(function)\nArgument:\124r petID\n\124cffaaaaaaReturns:\124r Whether the given petID is in the leveling queue.\n\nA few iterator functions are also provided if you need to compare a pet against others. These are used in a for loop such as:\n\n\124cffcccccc    for speciesID in \124cffffd200AllSpeciesIDs()\124cffcccccc do\n      -- do something with speciesID\n    end\124r\n\n\124cffffd200AllSpeciesIDs \124cffaaaaaa(iterator function)\nReturns:\124r The next speciesID of all existing unique pets.\n\n\124cffffd200AllPetIDs \124cffaaaaaa(iterator function)\nReturns:\124r The next petID of all owned pets.\n\n\124cffffd200AllPets \124cffaaaaaa(iterator function)\nReturns:\124r The next petID or speciesID of all pets in the master list. Owned pets return a petID string, uncollected pets return a speciesID number.\n\n\124cffffd200AllAbilities \124cffaaaaaa(iterator function)\nArgument:\124r speciesID\n\124cffaaaaaaReturns:\124r The next abilityID and level of the ability for a speciesID.\n\124cffffd200Note:\124r abilityList and levelList are already defined for each pet as your script runs. Use this iterator if you need to gather abilities of other pets for comparison. See the Unique Abilities script for an example.\n\n\124cffffd200If you would like anything else exposed please post a comment on wowinterface, curse or warcraftpet's Rematch 4.0 thread."] = nil

-- Dialogs\Collection.lua
	L["Total Collected Pets"] = "Total de mascotas capturadas"
	L["Unique Collected Pets"] = "Mascotas únicas capturadas"
	L["Pets Not Collected"] = "Mascotas no capturadas:"
	L["Percent Collected"] = "Porcentaje de mascotas capturadas"
	L["Max Level Pets"] = "Nivel máximo"
	L["Rare Quality Pets"] = "Calidad poco común:"
	L["Unique Pets In the Journal"] = "Mascotas únicas en el diario"
	L["Collection Statistics"] = "Estadísticas de la colección"
	L["There are %s%d\124r unique pets in the journal"] = "Existen %s%d\124r mascotas únicas en el diario."
	L["Pets Collected"] = "Capturadas:"
	L["Pets At Max Level"] = "Nivel máximo:"
	L["Total"] = "Total"
	L["Unique"] = "Única"
	L["Duplicate Collected Pets"] = "Duplicadas:"
	L["Average Battle Pet Level"] = "Nivel medio de las mascotas:"
	L["You have %s%.1f%%\124r of those unique pets"] = "Tienes el %s%.1f%%\124r de esas mascotas únicas"
	L["All unique pets in the journal. This is all obtainable unique pets."] = "Todas las mascotas únicas en el diario. Estas son todas las mascotas únicas que se pueden obtener."
	L["All pets you've collected, including duplicates."] = "Todas las mascotas que has capturado, incluyendo duplicados."
	L["The unique pets you've collected, not including duplicates."] = "Las mascotas únicas que has capturado, sin incluir duplicados."
	L["The unique pets you're missing."] = "Las mascotas únicas que te faltan."
	L["How much of each category's unique pets you've collected as a percent."] = "La cantidad de mascotas únicas de cada categoría que has recolectado como porcentaje."
	L["All of your level 25 pets, including duplicates."] = "Todas tus mascotas de nivel 25, incluyendo duplicados."
	L["All of your rare quality pets, including duplicates."] = "Todas tus mascotas de calidad poco común, incluyendo duplicados."
	L["Pet Types"] = "Familia"
	L["Sources"] = "Fuente"

-- Frames\Frame.lua
	L["Pets"] = "Mascotas"
	L["Options"] = "Opciones"
	L["Toggle Single Panel Mode"] = "Alternar modo de panel único"
	L["Toggle between one panel or two panels side by side."] = "Alternar entre un panel o dos paneles uno al lado del otro."
	L["You are in combat. Try again when out of combat."] = "Estás en combate. Inténtalo de nuevo cuando estés fuera de combate."

-- Frames\Configure.lua

-- Frames\Journal.lua
	L["Enable Rematch"] = "Activar Rematch"
	L["Check this to use Rematch in the pet journal."] = "Marca esto para usar Rematch en el diario de mascotas."

-- Process\Battle.lua
	L["Show Pet Card"] = "Mostrar tarjeta de mascota"

end
