local L = LibStub("AceLocale-3.0"):NewLocale("CC", "deDE")
if not L then return end

L["Add Spell"] = "Zauber hinzufügen"
L["All specified colors are vertex colors! (see wowwiki.com)"] = "Alle eingestellten Farben sind Vertex-Angaben! (siehe wowwiki.com)"
L["All unlockable modules are disabled!"] = "Alle freisetzbaren Module sind deaktiviert!"
L["Attach to cursor"] = "An Cursor anheften"
L["Auto arrange icons"] = "Symbole automatisch anordnen"
L["Background"] = "Hintergrund"
L["Bar"] = "Leiste"
L["Border"] = "Rahmen"
L["Bottom"] = "Unten"
L["Bottom has to be a number!"] = "Unten muss eine Zahl sein!"
L["Cast color"] = "Farbe für Zauber"
L["Casttime"] = "Zauberzeit"
L["Color"] = "Farbe"
L["Colors"] = "Farben"
L["Display"] = "Anzeige"
L["Enabled"] = "Aktiviert"
L["Font"] = "Schrift"
L["Font Size"] = "Schriftgröße"
L["General"] = "Allgemein"
L["Hide default castbar"] = "Verstecke Standardzauberleiste"
L["Horizontal Offset"] = "Horizontal Offset"
L["Icon size"] = "Symbolgröße"
L["Latency color"] = "Farbe für Latenz"
L["Left"] = "Links"
L["Left has to be a number!"] = "Links muss eine Zahl sein!"
L["Miscellaneous"] = "Sonstiges"
L["Position"] = "Position"
L["Primary"] = "Primär"
L["Radius"] = "Radius"
L["Remove Spell"] = "Zauber entfernen"
L["Restore defaults"] = "Standardwerte wiederherstellen"
L["Ring"] = "Ring"
L["Rotate"] = "Rotieren"
L["Secondary"] = "Sekundär"
L["Show spark only"] = "Zeige nur Funken"
L["Spark"] = "Funke"
L["Spell Text"] = "Zaubertext"
L["Spellcds"] = "Zauberabklingzeiten"
L["Spells"] = "Zauber"
L["Talent Specs"] = "Talentspezialisierungen"
L["Text"] = "Text"
L["Texture"] = "Textur"
L["Thickness"] = "Thickness"
L["Unlock"] = "Freisetzen"
--[[Translation missing --]]
L["Vertical Offset"] = "Vertical Offset"
--[[Translation missing --]]
L["x-Offset"] = "x-Offset"
--[[Translation missing --]]
L["y-Offset"] = "y-Offset"

